version: '1.0.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER
before_build:
- npm install
- node update-version.js
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\Mediator.Net" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.IoCTestUtil" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.Middlewares.Serilog" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.Test" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.Autofac" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.Autofac.Test" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.StructureMap" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.StructureMap.Test" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.Ninject" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.SimpleInjector" -c %CONFIGURATION% --no-dependencies
- dotnet build "src\Mediator.Net.SimpleInjector.Test" -c %CONFIGURATION% --no-dependencies


after_build:
- dotnet pack "src\Mediator.Net" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Autofac" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.StructureMap" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Ninject" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.SimpleInjector" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Middlewares.Serilog" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.IoCTestUtil" -c %CONFIGURATION% --no-build -o artifacts
test_script:
- dotnet test "src\Mediator.Net.Test" -c %CONFIGURATION%
- dotnet test "src\Mediator.Net.Autofac.Test" -c %CONFIGURATION%
- dotnet test "src\Mediator.Net.StructureMap.Test" -c %CONFIGURATION%
- dotnet test "src\Mediator.Net.SimpleInjector.Test" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Done