version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: Nuget restore
- ps: ./update-version.ps1
build:
  project: Mediator.Net.sln
  verbosity: minimal

after_build:
- dotnet pack "src\Mediator.Net" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Autofac" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.StructureMap" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Ninject" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.SimpleInjector" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.Middlewares.Serilog" -c %CONFIGURATION% --no-build -o artifacts
- dotnet pack "src\Mediator.Net.IoCTestUtil" -c %CONFIGURATION% --no-build -o artifacts

artifacts:
- path: artifacts\**\*.*

test_script:
- cmd: xunit.console "src\Mediator.Net.Test\bin\Debug\netcoreapp1.0\Mediator.Net.Test.dll"

cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Done